name: CommandBinder
version: '${project.version}'
main: de.hgpractice.commandbinder.CommandBinder
api-version: '1.20'
author: Creeper_craft
description: A plugin to bind commands to items. Inspired by the PServer-Plugin from NeruxVace.de
commands:
  commandbinder:
    aliases:
      - cb
      - cmdbinder
    description: Main command of the plugin
